<a href="https://colab.research.google.com/github/map72ru/linag/blob/main/%D0%B4%D0%B72.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

__1__ Установить, какие произведения матриц  AB  и  BA  определены, и найти размерности полученных матриц:

а)  A  — матрица  4×2 ,  B  — матрица  4×2 ;

б)  A  — матрица  2×5 ,  B  — матрица  5×3 ;

в)  A  — матрица  8×3 ,  B  — матрица  3×8 ;

г)  A  — квадратная матрица  4×4 ,  B  — квадратная матрица  4×4 .


a) A\*B - не определено, B\*A - не определено

б) А\*В - определено, результирующая матрица 2 х 3, B\*A - не определено

в) А\*В - определено, результирующая матрица 8х8, В\*А - определено, результипующая матрица 3х3 

г) А\*В - определено, результирующая матрица 4х4, В\*А - определено, результирующая матрица 4х4

__2__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$A+B$ = $\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} + \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}$ = $\begin{pmatrix}
1 + 4 & -2 -1\\ 
3 + 0 & 0 + 5
\end{pmatrix}$ = $\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$

<br>
<br>

$A*B$ = $\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} * \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}$ = $\begin{pmatrix}
1 * 4 + (-2) * 0 & 1 * (-1) + (-2) * 5\\ 
3 * 4 + 0 * 0 & 3 * (-1) + 0 * 5
\end{pmatrix}$ = $\begin{pmatrix}
2 & -11\\ 
12 & -3
\end{pmatrix}$

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

<br>
$3A-2B+4C$ = $3 * \begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$ + $2 * \begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$ + $4 * \begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}$ = $\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix}$ + $\begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix}$ + $\begin{pmatrix}
8 & -16\\ 
3 & 3
\end{pmatrix}$ = $\begin{pmatrix}
11 & 15\\ 
16 & -17
\end{pmatrix}$


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$A^{T} = \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\\ 
\end{pmatrix}$.

<br>

$AA^{T} = \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} * \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\\ 
\end{pmatrix} = \begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13\\ 
\end{pmatrix}$

<br>

$A^{T}A = \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\\ 
\end{pmatrix} * \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} = \begin{pmatrix}
45 & 0\\ 
0 & 14
\end{pmatrix}$



In [ ]:
import numpy as np
A = np.array([[4, 1], [5, -2], [2, 3]])
np.dot(A, A.T)

[[17 18 11]
 [18 29  4]
 [11  4 13]]


In [ ]:
np.dot(A.T, A)

array([[45,  0],
       [ 0, 14]])

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [ ]:
def size(A):
    m = len(A)
    if m == 0:
        return (0, 0)
    n = len(A[0])
    for r in A[1:]:
        if len(r) != n:
            raise Exception('Invalid matrix size')

    return (m, n)

def rowMulti(r, c):
    s = 0
    k = 0
    for m in r:
        s = s + m*c[k]
        k = k+1
    return s

def multi(A, B):
    sizeA = size(A)
    sizeB = size(B)
    if sizeA[1] != sizeB[0]:
        raise Exception("Matrix A and B cannot be multiplied")
    m = 0
    C = [[0] * sizeB[1] for i in range(sizeA[0])]
    for r in A:
        n = 0
        while n < sizeB[1]:
            C[m][n] = rowMulti(r, [row[n] for row in B])
            n = n+1
        m = m + 1
    return C

A = [[4, 1], [5, -2], [2, 3]]
B = [[5, 4], [6, 7]]
print(size(A))
print(size(B))
print(multi(A,B))

A = [[1, 2], [3, 4]]
B = [[1, 3], [2, 4]]
print(size(A))
print(size(B))
print(multi(A,B))


(3, 2)
(2, 2)
[[26, 23], [13, 6], [28, 29]]
(2, 2)
(2, 2)
[[5, 11], [11, 25]]


Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} = sinx * sinx - (-cosx) * cosx = sin^2x + cos^2x = 1$$ 

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = 4 * \begin{vmatrix}
5 & 1\\ 
0 & 9
\end{vmatrix} - 2 * \begin{vmatrix}
0 & 1\\ 
0 & 9
\end{vmatrix} + 3 * \begin{vmatrix}
0 & 5\\ 
0 & 0
\end{vmatrix} = 4 * (9 * 5 - 1 * 0) - 2 * (0 * 9 - 1 * 0) + 3 (0 * 0 - 5 * 0) = 4 * 45 - 0 + 0 = 180$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = 1 * (5*9-6*8) - 2*(4*9-6*7) + 3*(4*8-5*7)=-3+12-9=0$$

In [2]:
import numpy as nm

A = nm.array([[4,2,3],[0,5,1],[0,0,9]])
nm.linalg.det(A)

180.0

In [3]:
A = nm.array([[1,2,3],[4,5,6],[7,8,9]])
nm.linalg.det(A)

0.0

__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2}) = 16$;
    
   б) $det(A^{T}) = 4$;
    
   в) $det(2A) = 8$.

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$

вырождена.

Вырожденная матрица, это такая мптрица у которой детерминант равен 0.

 $det(A) = -2*(-14*13-6*7) - 7*(4*13+3*6)-3*(4*7-3*14) = 448-490+42=0$

In [4]:
A = nm.array([[-2,7,-3],[4,-14,6],[-3,7,13]])
nm.linalg.det(A)

0.0

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

Третья строка равна сумме первой и второй строк, поэтому ее можно отбросить. Первая строка не вырожается через вторую. Т.О. ранг матрицы равен 2.

$$det(A) = 1 * (1*3-2*1)-2*(1*4-1*2)+3*(1*3-2*1)=1-4+3=0$$

$$det(\begin{pmatrix}
1 & 2\\ 
1 & 1\\
\end{pmatrix}) = 3*1-2*1=-1 <> 0$$

   б) $$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$$

Третья строка есть сумма первой и второй, ее можно отбросить. Остальные строки нельзя выразить через комбинацию других строк. Т.О. ранг матрицы равен 3.

$$det(A) = 0$$

$$det(\begin{pmatrix}
0 & 2 & 2\\ 
0 & 4 & 3\\ 
3 & 5 & 6\\ 
\end{pmatrix}) = 0*(4*6-5*3)-2*(0*5-3*4)+2*(5*0-4*3)=-24 <> 0$$



In [8]:
A = nm.array([[1,2,3],[1,1,1],[2,3,4]])
nm.linalg.matrix_rank(A)

0.0

In [7]:
A = nm.array([[0,0,2,1],[0,0,2,2],[0,0,4,3],[2,3,5,6]])
nm.linalg.matrix_rank(A)

3