<a href="https://colab.research.google.com/github/map72ru/linag/blob/main/%D0%94%D0%974.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$


Составим расширенную матрицу:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
2 & 1 & -1 & 1\\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$

Умножим первую строку на 2 вычтем из второй:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
0 & -1 & 1 & 5\\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$

Из третьей строки вычтем первую:
$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
0 & -1 & 1 & 5\\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$

Система имеет бесконечное множество решений. Из последней строки матрицы составим уравнение:

$$-2 * x_{3} + 3 * x_{4} = 4$$

Таким образом: 

$$x_{3} = -2 + 3/2 * x_{4}$$

Если примем $x_{4}=c$, то $x_{3} = -2 + 3/2*c$, тогда

$$ -x_{2} + x_{3} + 5 * x_{4} = -2$$
или
$$-x_{2} + -2 + 3/2*c + c = -2$$
или
$$x_{2}= 5/2*c $$
Все подставляем в первое уравнение:

$$x_{1} + 5/2*c + 2 - 3/2*c - 2*c = 0$$
или
$$x_{1} = c - 2$$

Запишем все вместе:

$$\begin{cases}
x_{1}= c - 2 \\
x_{2}= 5/2*c \\
x_{3}= -2 + 3/2*c \\
x_{4}= c
\end{cases}$$

Частное решение при $c = 0, x_{1} = -2, x_{2} = 0, x_{3} = -2, x_{4} = 0$. Проверим:

$$\begin{cases}
-2+0+2-2*0=0, \\
2*-2+0+2+0=-2, \\
-2+0-3*(-2)+0=4.
\end{cases}$$

Все равенства выполняются.



__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$

$$\tilde A = \begin{pmatrix}
\left.\begin{matrix}
3 & -1 & 1\\ 
2 & -5 & -3\\ 
1 & 1 & -1
\end{matrix}\right|
\begin{matrix}
4\\ 
-17\\
0
\end{matrix}
\end{pmatrix}$$


In [ ]:
import numpy as nm

In [ ]:
A = nm.array([[3,-1,1], [2, -5, -3], [1, 1, -1]])
nm.linalg.matrix_rank(A)

3

In [ ]:
At = nm.concatenate([A, nm.array([[4], [-17], [0]])], axis=1)
nm.linalg.matrix_rank(At)

3

Т.к. $rank A = rank \tilde A$, то система уровнений совместна и будет иметь единственное решение.

б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$

Если умножить второе уравнение на 3 и вычесть из третьего, то получим следующую систему уровнений:

$\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
0x_{1}-0x_{2}+0x_{3}=11;
\end{cases}$

Таким образим, система не совместна и решения нет.

в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

$\tilde A = \begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 5\\ 
3 & 1 & -8
\end{matrix}\right|
\begin{matrix}
4\\ 
-2
\end{matrix}
\end{pmatrix}$

Ранг матрицы $A$ и $\tilde A$ равен 2. Поэтому система имеет бесконечное множество решений.

__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

In [ ]:
A = nm.array([[1,3,-2,4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
nm.linalg.matrix_rank(A)

4

In [ ]:
At = nm.concatenate([A, nm.array([[3], [2], [4], [1]])], axis=1)
nm.linalg.matrix_rank(At)

4

Т.к. $rank A = rank \tilde A$, то система уровнений совместна и будет иметь единственное решение.

__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

Запишем в виде системы уравнений:

$\begin{cases}
x_{1}+2x_{2}+3x_{3}=a, \\
4x_{1}+5x_{2}+6x_{3}=b, \\
7x_{1}+8x_{2}+9x_{3}=c;
\end{cases}$

Первое уровнение умножим на 4 и вычтем из второго, так же умножим первое уровнение на 7 и вычтем из третьего. Получим следующую систему:

$\begin{cases}
x_{1}+2x_{2}+3x_{3}=a, \\
-3x_{2}-6x_{3}=b-4a, \\
-6x_{2}-12x_{3}=c-7a;
\end{cases}$

Умножим второе уровнение на -2 и сложим с третьим уравнением:
$$\begin{cases}
x_{1}+2x_{2}+3x_{3}=a, \\
-3x_{2}-6x_{3}=b-4a, \\
0x_{2}-0x_{3}=(c-7a)+-2\cdot(b-4a);
\end{cases}$$

Что бы данная система была несовместна необходимо, что бы $(c-7a)+-2\cdot(b-4a) \neq 0$

или **$c+a \neq 2b$**.


__5.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$

$det A = 1*(-4)-3*(-2) = 2$

$det A_1 = 1*(-4)-7*(-2) = 10$

$det A_2 = 1*7-1*3 = 4$

$x_1 = 10 / 2 = 5$

$x_2 = 4 / 2 = 2$

   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

$A = \begin{pmatrix}
2 & -1 & 5\\ 
1 & 1 & -3\\ 
2 & 4 & 1
\end{pmatrix}$

$det A = 2*(1*1+3*4) + (1*1+2*3) + 5 * (1*4-2*1)=26+7+10=43$

$A_1 = \begin{pmatrix}
10 & -1 & 5\\ 
-2 & 1 & -3\\ 
1 & 4 & 1
\end{pmatrix}$

$det A_1 = 10*(1*1+3*4) + (-2*1+1*3) + 5 * (-2*4-1*1)=130+1-45=86$

$A_2 = \begin{pmatrix}
2 & 10 & 5\\ 
1 & -2 & -3\\ 
2 & 1 & 1
\end{pmatrix}$

$det A_2 = 2*(-2*1+3*1) - 10*(1*1+2*3) + 5*(1*1+2*2)=2-70+25=-43$

$A_3 = \begin{pmatrix}
2 & -1 & 10\\ 
1 & 1 & -2\\ 
2 & 4 & 1
\end{pmatrix}$

$det A_3 = 2*(1*1+2*4) + (1*1+2*2) + 10*(1*4-2*1)=18+5+20=43$

$x_1 = 86/43=2$

$x_2 = 97/43 = -1$

$x_3 = 43/43 = 1$


In [ ]:
A = nm.array([[2,-1,5], [1,1, -3], [2, 4, 1]])
nm.linalg.det(A)

42.99999999999998

In [ ]:
A = nm.array([[10,-1,5], [-2,1, -3], [1, 4, 1]])
nm.linalg.det(A)

86.00000000000004

In [ ]:
A = nm.array([[2,10,5], [1,-2, -3], [2, 1, 1]])
nm.linalg.det(A)

-43.000000000000014

In [ ]:
A = nm.array([[2,-1,10], [1,1, -2], [2, 4, 1]])
nm.linalg.det(A)

42.99999999999998

__2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$

Умножим первую строку матрицы на 2 и вычтем из второй строки:

1 шаг
$$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
3 & 26 & 30
\end{pmatrix}$$

$$L = \begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
l_{13} & l_{23} & 1
\end{pmatrix}$$

Умножим первую строку матрицы на 3 и вычтем из третьей строки:

2 шаг
$$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix}$$

$$L = \begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & l_{23} & 1
\end{pmatrix}$$

Умножим вторую строку измененной матрицы, полкченной на втором шаге на 4 и вычтем из третьей строки:

3 шаг
$$U = \begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}$$

$$L = \begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}$$

   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

1 шаг. Для первой строки коэффициенты матрицы L будут 2,3,4:

$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
0 & 18 & 45 & 17
\end{pmatrix}$$

$$L = \begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & l_{32} & 1 & 0\\
4 & l_{42}& l_{43} & 1
\end{pmatrix}$$

2 шаг. Для второй строки коэффициенты матрицы L будут 5, 6:

$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 21 & 11
\end{pmatrix}$$

$$L = \begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\
4 & 6 & l_{43} & 1
\end{pmatrix}$$

3 шаг. Для третьей строки коэффициенты матрицы L будут 7:

$$U = \begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix}$$

$$L = \begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\
4 & 6 & 7 & 1
\end{pmatrix}$$

In [ ]:
L = nm.array([[1, 0, 0, 0], [2, 1, 0, 0], [3, 5, 1, 0], [4, 6, 7, 1]])
U = nm.array([[1, 1, 2, 4], [0, 3, 4, 1], [0, 0, 3, 1], [0, 0, 0, 4]])

L.dot(U)

array([[ 1,  1,  2,  4],
       [ 2,  5,  8,  9],
       [ 3, 18, 29, 18],
       [ 4, 22, 53, 33]])

__3*.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

Запишем матрицу и сделаем LU разложение:
$$\begin{pmatrix}
2 & 1 & 3 \\ 
11 & 7 & 5 \\ 
9 & 8 & 4
\end{pmatrix}$$

Для первого столбца коэффициенты матрицы будут 5,5 и 4,5:

$$\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 1,5 & -11,5 \\ 
0 & 3,5 & -9,5
\end{pmatrix}$$

$$L = \begin{pmatrix}
1 & 1 & 0 \\ 
5,5 & 1 & 0 \\ 
4,5 & l_{23} & 1
\end{pmatrix}$$

Для второго столбца коэффициент матрицы L будет 7/3:

$$U=\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 1,5 & -11,5 \\ 
0 & 0 & 17,(33)
\end{pmatrix}$$

$$L = \begin{pmatrix}
1 & 0 & 0 \\ 
5,5 & 1 & 0 \\ 
4,5 & 2,(33) & 1
\end{pmatrix}$$

Проверка:


In [ ]:
L = nm.array([[1, 0, 0], [5.5, 1, 0], [4.5, 2.33333333, 1]])
U = nm.array([[2, 1, 3], [0, 1.5, -11.5], [0, 0, 17.333333333]])

L.dot(U)

array([[ 2.        ,  1.        ,  3.        ],
       [11.        ,  7.        ,  5.        ],
       [ 9.        ,  7.99999999,  4.00000004]])

Решим теперь систему 

$$Ly=b:$$

$$\begin{cases}
y_{1}=1, \\
5.5y_{1}+y_{2}=-6, \\
4.5y_{1}+2.33333y_{2}+y_{3}=-5.
\end{cases}$$

$$y_{1}=1,$$
$$y_{2}=-11.5,$$
$$y_{3}=-5-4.5+2.33333*11.5=17.333295.$$

И затем систему

$$Ux=y:$$

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1, \\
1.5x_{2}-11.5x_3=-11.5, \\
17.3333333x_{3}=17.333295.
\end{cases}$$

$$x_{3}=1,$$
$$x_{2}=0,$$
$$x_{1}=-1.$$

Подстановка решения в исходную систему показывает, что равенство выполняется.

__4*.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

Произведем разложение на $LL^{T}$:

$$l_{11}=\sqrt{a_{11}}=\sqrt{81} = 9,$$
$$l_{21}=\frac{a_{21}}{l_{11}}=\frac{-45}{9}=-5,$$
$$l_{31}=\frac{a_{31}}{l_{11}}=\frac{45}{9}=5,$$

$$l_{22}=\sqrt{a_{22}-l_{21}^{2}}=\sqrt{50 - 25}=5,$$
$$l_{32}=\frac{1}{l_{22}}\left(a_{32}-l_{21}l_{31} \right)=\frac{1}{5}\left ( -15 + 25\right)=2,$$

$$l_{33}=\sqrt{a_{33}-l_{31}^{2}-l_{32}^{2}}=\sqrt{38-25-4}=3.$$

Получили матрицу:

$$L = \begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix},$$ 

$$L^{T} = \begin{pmatrix}
9 & -5 & 5 \\ 
0 & 5 & 2 \\ 
0 & 0 & 3
\end{pmatrix}.$$

Решим систему $Ly=b:$

$$\begin{cases}
9y_{1}=531, \\
-5y_{1}+5y_{2}=-460, \\
5y_{1}+2y_{2}+3y_{3}=193.
\end{cases}$$

$$y_{1} = 59,$$

$$y_{2}=-33,$$

$$y_{3}=\frac{193-295+66}{3}=-12.$$

И решим систему $L^{T}x=y:$

$$\begin{cases}
9x_{1}-5x_{2}+5x_{3}=59, \\
5x_{2}+2x_{3}=-33, \\
3x_{3}=-12.
\end{cases}$$

$$x_{3}=-4,$$

$$x_{2}=\frac{-33+2\cdot4}{5}=-5,$$

$$x_{1}=\frac{59-25+20}{9}=6.$$

Проверка:

$$\begin{cases}
81*6-45*(-5)+45*(-4)=531 \\
-45*6+50*(-5)-15*(-4)=-460 \\
45*6-15*(-5)+38*(-4)=193
\end{cases}$$

Выполняется.

In [2]:
import numpy as nm


def cramar(slae: nm.array):
    """
    Возвращает решение системы линейных уравнений методом Крамера.

    :param slae: расширенная матрица размером N x N+1
    :return: вектор решения уравнений

    Если система не имеет решения, то возвращается ошибка.
    """
    n = nm.size(slae, axis=0)
    m = nm.size(slae, axis=1)
    if n+1 != m:
        raise ValueError("Size of input matrix invalid. Must be N x N+1")

    A = slae[:n, :n]
    B = slae[:, m-1]
    detA = nm.linalg.det(A)
    if detA <= 0.000000000001:
        raise ValueError(f'This system has no solution. Det: {detA}')

    X = nm.empty(n)

    l = 0
    while l < n:
        C = nm.copy(A)
        C[:,l] = B
        X[l] = nm.linalg.det(C)/detA
        l = l+1

    return X


A = nm.array([[2, -1, 5, 10], [1, 1, -3, -2], [2, 4, 1, 1]])
print(cramar(A))


[ 2. -1.  1.]
